// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStorageSetting = "storage_settings"

// StorageSetting 存储平台配置
type StorageSetting struct {
	ID                 string    `gorm:"column:id;primaryKey;comment:id" json:"id"`                                      // id
	PlatformIdentifier string    `gorm:"column:platform_identifier;not null;comment:存储平台标识符" json:"platform_identifier"` // 存储平台标识符
	ConfigData         string    `gorm:"column:config_data;not null;comment:存储配置" json:"config_data"`                    // 存储配置
	Enabled            bool      `gorm:"column:enabled;not null;comment:是否启用 0：否 1：是" json:"enabled"`                    // 是否启用 0：否 1：是
	UserID             string    `gorm:"column:user_id;not null;comment:所属用户" json:"user_id"`                            // 所属用户
	CreatedAt          time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                               // 创建时间
	UpdatedAt          time.Time `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                               // 更新时间
	Remark             string    `gorm:"column:remark;comment:备注" json:"remark"`                                         // 备注
	Deleted            bool      `gorm:"column:deleted;comment:逻辑删除 0未删除 1已删除" json:"deleted"`                           // 逻辑删除 0未删除 1已删除
}

// TableName StorageSetting's table name
func (*StorageSetting) TableName() string {
	return TableNameStorageSetting
}
