// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStoragePlatform = "storage_platform"

// StoragePlatform 存储平台
type StoragePlatform struct {
	ID           int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:存储平台" json:"id"`                  // 存储平台
	Name         string `gorm:"column:name;not null;comment:存储平台名称" json:"name"`                                 // 存储平台名称
	Identifier   string `gorm:"column:identifier;not null;comment:存储平台标识符" json:"identifier"`                    // 存储平台标识符
	ConfigScheme string `gorm:"column:config_scheme;not null;comment:存储平台配置描述schema" json:"config_scheme"`       // 存储平台配置描述schema
	Icon         string `gorm:"column:icon;comment:存储平台图标" json:"icon"`                                          // 存储平台图标
	Link         string `gorm:"column:link;comment:存储平台链接" json:"link"`                                          // 存储平台链接
	IsDefault    int32  `gorm:"column:is_default;not null;default:1;comment:是否默认存储平台 0-否 1-是" json:"is_default"` // 是否默认存储平台 0-否 1-是
	Desc         string `gorm:"column:desc;comment:存储平台描述" json:"desc"`                                          // 存储平台描述
}

// TableName StoragePlatform's table name
func (*StoragePlatform) TableName() string {
	return TableNameStoragePlatform
}
